const sidebars = {
  hardwareSidebar: [{type: "autogenerated", dirName: "1-hardware"}],
  softwareSidebar: [{type: "autogenerated", dirName: "2-software"}],
  firmwareSidebar: [{type: "autogenerated", dirName: "3-firmware"}],
  architectureSidebar: [{type: "autogenerated", dirName: "4-architecture"}],
};

module.exports = sidebars;
